export default [
    {
        key: '0',
        day: 8,
        month: 2,
        year: 2020,
        time: '10:30:23',
        event: 'событие0',
        repeating: true,
        position: 'left',
        prior: 'высокий',
    },{
        key: '1',
        day: 4,
        month: 11,
        year: 2020,
        time: '10:30:12',
        event: 'событие1',
        repeating: true,
        position: 'left',
        prior: 'высокий',
    },
    {
        key: '2',
        day: 11,
        month: 10,
        year: 2019,
        time: '09:31',
        event: 'событие21',
        repeating: false,
        position: 'left',
        prior: 'средний',
    },
    {
        key: '3',
        day: 12,
        month: 10,
        year: 2019,
        time: '19:31:32',
        event: 'событие3',
        repeating: false,
        position: 'left',
        prior: 'низкий',
    },
    {
        key: '4',
        day: 23,
        month: 11,
        year: 2019,
        time: '19:31:00',
        event: 'событие4',
        repeating: false,
        position: 'left',
        prior: 'высокий',
    },
    {
        key: '5',
        day: 22,
        month: 1,
        year: 2019,
        time: '12:31:39',
        event: 'событие5',
        repeating: false,
        position: 'left',
        prior: 'низкий',
    },
]
